In [1]:
import numpy as np

In [10]:
ar = np.array([10,20,30])

In [11]:
print(type(ar))
ar+5

<class 'numpy.ndarray'>


array([15, 25, 35])

In [12]:
ar.shape

(3,)

In [15]:
twod_list = [[10,20], [20,30], [40,50]]
a = np.array(twod_list)
a.shape


(3, 2)

In [30]:
list = [[10,20],[30,40],[50,60]]
a = np.array(list)
a[1,0]

30

In [34]:
#slicing
list2 = [[10,20],[30,40],[50,60]]
a = np.array(list2)
print(a[:,1:]) #listname = [row range, column range]
a*5



[[20]
 [40]
 [60]]


array([[ 50, 100],
       [150, 200],
       [250, 300]])

In [6]:
#zero function
x = np.zeros((1,5))
x

array([[0., 0., 0., 0., 0.]])

In [13]:
#ones function
y = np.ones((2,4))
a = np.ones((2,5), dtype = 'int')
y
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
#full function
z = np.full((2,2),1000)
z

array([[1000, 1000],
       [1000, 1000]])

In [12]:
#to check documentation of a function,codes are also given in end(examples)
np.zeros?

In [14]:
#arange function, 1d array are always allocated in vertical memory
d = np.arange(10)
d.shape

(10,)

In [29]:
#to convert 1d to 2d,reshape function,prime numbers cannot be reshaped, reshaped value and array value should be equal
e = np.arange(1,101)
e2 = np.reshape(e, (5,20))
e2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [38]:
#eye function
f = np.eye(4,4,0)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
#random function, generates 1d array
g = np.random.random(10)
g
g2 = np.reshape(g, (5,2))
g2

array([[0.65034054, 0.79498057],
       [0.74635621, 0.66865638],
       [0.82684832, 0.36664195],
       [0.90739443, 0.20409186],
       [0.61331879, 0.19180818]])

In [52]:
e = np.arange(1,11)
e2 = np.reshape(e, (5,2))
e3 = e2[2:7,2:7]
e3

array([], shape=(3, 0), dtype=int32)

In [56]:
#for and = & and for or = |
filter = (e2>4) | (e2<8)
filter

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [9]:
#for squareroot = sqrt, for exponent = exp
array = np.array([4,6,9,12,25,45,36,81,100,200,541,343,729,564,502])
a = np.reshape(array, (3,5))
np.sqrt(a)

array([[ 2.        ,  2.44948974,  3.        ,  3.46410162,  5.        ],
       [ 6.70820393,  6.        ,  9.        , 10.        , 14.14213562],
       [23.2594067 , 18.52025918, 27.        , 23.74868417, 22.4053565 ]])

In [18]:
#add
add1 = np.array([[20,30],[40,50]])
add2 = np.array([[60,70],[80,90]])
add1+add2 #simple add symbol
#or
print(np.add(add1,add2))

[[ 80 100]
 [120 140]]


In [20]:
#subtract
add1-add2
np.subtract(add1,add2)

array([[-40, -40],
       [-40, -40]])

In [22]:
#multiply
add1*add2
np.multiply(add1,add2)

array([[1200, 2100],
       [3200, 4500]])

In [24]:
#divide
add1/add2
np.divide(add1,add2)

array([[0.33333333, 0.42857143],
       [0.5       , 0.55555556]])

In [3]:
#randn function
random_ = np.random.randn(5,5)
random_

array([[-3.14726743e-01,  9.61653235e-01,  2.80707080e+00,
        -8.19686190e-01,  1.06657393e+00],
       [-6.18119792e-01, -1.14303569e+00, -1.23974218e+00,
        -4.41192431e-01, -8.76319560e-01],
       [ 5.11469853e-01, -1.56737449e+00,  6.22910899e-01,
         1.86242170e+00,  1.82766029e-01],
       [ 4.71430476e-01, -8.85282979e-01,  3.31817128e-01,
         4.12056738e-02,  2.79195774e+00],
       [ 2.23129300e-01, -1.35487059e+00,  4.61111340e-01,
         2.51204148e-04, -9.72989965e-01]])

In [4]:
#mean func
random_.mean()

0.08409714787467686